"""empty message

Revision ID: 2b51ed64145a
Revises: ade6d27a6639
Create Date: 2020-07-05 01:27:46.237958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b51ed64145a"
down_revision = "ade6d27a6639"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newspaper", sa.Column("twitter_access_token_key", sa.String(), nullable=True)
    )
    op.add_column(
        "newspaper",
        sa.Column("twitter_access_token_secret", sa.String(), nullable=True),
    )
    op.drop_column("newspaper", "access_token_key")
    op.drop_column("newspaper", "access_token_secret")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newspaper",
        sa.Column(
            "access_token_secret", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "newspaper",
        sa.Column("access_token_key", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("newspaper", "twitter_access_token_secret")
    op.drop_column("newspaper", "twitter_access_token_key")
    # ### end Alembic commands ###
