"""empty message

Revision ID: 2fc8c9942744
Revises: 
Create Date: 2020-07-05 00:30:59.159001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fc8c9942744"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_article_revision_changed_at"),
        "article_revision",
        ["changed_at"],
        unique=False,
    )
    op.drop_index("articlerevision_changed_at", table_name="article_revision")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "articlerevision_changed_at", "article_revision", ["changed_at"], unique=False
    )
    op.drop_index(op.f("ix_article_revision_changed_at"), table_name="article_revision")
    # ### end Alembic commands ###
