"""empty message

Revision ID: 6cd2c068d0bf
Revises: 2b51ed64145a
Create Date: 2020-07-05 03:12:40.945257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cd2c068d0bf"
down_revision = "2b51ed64145a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article_revision", "body")
    op.drop_column("newspaper", "article_body_css_selector")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newspaper",
        sa.Column(
            "article_body_css_selector",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "article_revision",
        sa.Column("body", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
