"""empty message

Revision ID: ade6d27a6639
Revises: 2fc8c9942744
Create Date: 2020-07-05 01:26:16.676881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ade6d27a6639"
down_revision = "2fc8c9942744"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newspaper", sa.Column("access_token_key", sa.String(), nullable=True)
    )
    op.add_column(
        "newspaper", sa.Column("access_token_secret", sa.String(), nullable=True)
    )
    op.add_column(
        "newspaper", sa.Column("twitter_consumer_key", sa.String(), nullable=True)
    )
    op.add_column(
        "newspaper", sa.Column("twitter_consumer_secret", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newspaper", "twitter_consumer_secret")
    op.drop_column("newspaper", "twitter_consumer_key")
    op.drop_column("newspaper", "access_token_secret")
    op.drop_column("newspaper", "access_token_key")
    # ### end Alembic commands ###
